import Foundation

enum BatteryHealthText {
    static let placeholder = String(localized: .batteryHealthPlaceholder)
    static let awaitingSample = String(localized: .batteryHealthDatasetAwaitingSample)
    static let validated = String(localized: .batteryHealthDatasetValidated)
    static let summary = String(localized: .batteryHealthSectionSummary)
    static let pack = String(localized: .batteryHealthSectionPack)
    static let charging = String(localized: .batteryHealthSectionCharging)
    static let cells = String(localized: .batteryHealthSectionCells)
    static let temperatures = String(localized: .batteryHealthSectionTemperatures)
    static let dataSources = String(localized: .batteryHealthSectionDataSources)
    static let chargePowerControl = String(localized: .batteryHealthSectionChargePower)
    static let noValidatedCells = String(localized: .batteryHealthCellsEmpty)
    static let noValidatedTemperatures = String(localized: .batteryHealthTemperaturesEmpty)
    static let copyLog = String(localized: .batteryHealthCopyLogButton)
    static let attention = String(localized: .batteryHealthSectionAttention)
    static let liveSummary = String(localized: .batteryHealthSectionLiveSummary)
    static let details = String(localized: .batteryHealthSectionDetails)
    static let packRange = String(localized: .batteryHealthSectionPackRange)
    static let awaitingCellData = String(localized: .batteryHealthCellsAwaitingTitle)
    static let awaitingCellDataDetail = String(localized: .batteryHealthCellsAwaitingDetail)
    static let healthDistribution = String(localized: .batteryHealthSectionHealthDistribution)
    static let normal = String(localized: .batteryHealthCellConditionNormal)
    static let critical = String(localized: .batteryHealthCellConditionCritical)
    static let activeCells = String(localized: .batteryHealthMetricActiveCells)
    static let balancing = String(localized: .batteryHealthCellBalancing)
    static let balancingExplanation = String(localized: .batteryHealthBalancingExplanation)
    static let cellDeviation = String(localized: .batteryHealthSectionCellDeviation)
    static let noDecodedCells = String(localized: .batteryHealthCellsNoDecoded)
    static let minimum = String(localized: .batteryHealthMetricMinimum)
    static let average = String(localized: .batteryHealthMetricAverage)
    static let maximum = String(localized: .batteryHealthMetricMaximum)
    static let delta = String(localized: .batteryHealthMetricDelta)
    static let belowAverage = String(localized: .batteryHealthCellConditionBelowAverage)
    static let aboveAverage = String(localized: .batteryHealthCellConditionAboveAverage)
    static let temperatureRange = String(localized: .batteryHealthSectionTemperatureRange)
    static let awaitingTemperatures = String(localized: .batteryHealthTemperaturesAwaitingTitle)
    static let awaitingTemperaturesDetail = String(localized: .batteryHealthTemperaturesAwaitingDetail)
    static let sensors = String(localized: .batteryHealthSectionSensors)
    static let noDecodedSensors = String(localized: .batteryHealthSensorsNoDecoded)
    static let chargingStatus = String(localized: .batteryHealthSectionChargingStatus)
    static let supportedControls = String(localized: .batteryHealthSectionSupportedControls)
    static let controlsUnavailable = String(localized: .batteryHealthChargeControlsUnavailableTitle)
    static let controlsUnavailableDetail = String(localized: .batteryHealthChargeControlsUnavailableDetail)
    static let actions = String(localized: .batteryHealthSectionActions)
    static let copyAll = String(localized: .batteryHealthActionCopyAll)
    static let export = String(localized: .batteryHealthActionExport)
    static let rawFlags = String(localized: .batteryHealthSectionRawFlags)
    static let state = String(localized: .batteryHealthMetricState)
    static let captured = String(localized: .batteryHealthMetricCaptured)
    static let bytes = String(localized: .batteryHealthMetricBytes)
    static let copyHexadecimal = String(localized: .batteryHealthActionCopyHexadecimal)
    static let chargeOperationAudit = String(localized: .batteryHealthSectionChargeOperationAudit)
    static let noChargeOperations = String(localized: .batteryHealthChargeOperationsEmpty)
    static let powerLimit = String(localized: .batteryHealthChargeControlPowerLimit)
    static let chargeTarget = String(localized: .batteryHealthChargeControlChargeTarget)
    static let cellDeviationAccessibility = String(localized: .batteryHealthAccessibilityCellDeviation)
    static let temperatureRangeAccessibility = String(localized: .batteryHealthAccessibilityTemperatureRange)

    static func cellPosition(_ position: Int) -> String {
        String(localized: .batteryHealthCellPosition(position))
    }

    static func sensorPosition(_ position: Int) -> String {
        String(localized: .batteryHealthSensorPosition(position))
    }

    static func cellDistributionAccessibility(normal: Int, attention: Int, critical: Int) -> String {
        String(localized: .batteryHealthAccessibilityCellDistribution(normal, attention, critical))
    }
}
